name: Github Actions
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.1.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_COVERAGE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
          